//! Procedural objects (Object › Procedural): Graphite-style node graphs that generate art.
//!
//! A procedural object is a group carrying a [`ProcGraph`] (`Node::procedural`); its children are
//! generated by `vectorcraft-procedural` and are ordinary nodes, so rendering, export, hit
//! testing, copy/paste and collaboration treat it like any group. Every edit of the graph
//! regenerates the children in the same undo step. Moving, rotating or scaling the group is
//! remembered in the graph's `transform`, so regenerating keeps the art where the user put it.
//!
//! Slider drags: run `procedural.setParam` as a live interaction (`Session::begin_interaction`,
//! `Session::preview` per step, `Session::commit_interaction`), which makes the drag one undo step.
//! Evaluation results are cached per graph node, so a drag re-runs only the nodes downstream of
//! the edited one.
//!
//! The JSON shapes here are the API the node-graph panel builds on: see `docs/procedural.md`.

use std::cell::RefCell;
use std::collections::{HashMap, VecDeque};
use std::sync::Arc;

use serde_json::{Map, Value, json};
use vectorcraft_doc::procedural::Link;
use vectorcraft_doc::{Document, Node, NodeId, ProcGraph};
use vectorcraft_geom::{Affine, Point};
use vectorcraft_procedural::{self as procgen, Cache, Diagnostic, Level};

use super::edit::selected_roots;
use super::*;
use crate::MAX_COORD;

pub fn specs() -> Vec<CommandSpec> {
    vec![
        cmd!(
            "procedural.create",
            "Make",
            ["Object", "Procedural"],
            None,
            "{preset?: id (procedural.presets), graph?: ProcGraph JSON, x?, y?: where the graph origin goes (default: the first artboard's centre), seed?, name?} make a procedural object; with neither preset nor graph, the selection becomes a `source.art` node (or the `flower` preset when nothing is selected) → {id, errors}",
            has_doc,
            create
        ),
        cmd!(query "procedural.presets", "Procedural Presets", [], None, "{} → [{id, label, doc}]", always, presets),
        cmd!(
            query "procedural.catalogue",
            "Procedural Node Catalogue",
            [],
            None,
            "{} → {version, categories, kinds: [{kind, label, category, doc, inputs: [{name, label, type, doc}], variadic, outputs, params: [{name, label, type: number|integer|bool|choice|color|palette, default, min?, max?, options?, doc}]}]}",
            always,
            catalogue
        ),
        cmd!(query "procedural.get", "Procedural Graph", [], None, "{id?} the procedural object (id, or the selected one) → {id, graph, errors, items}", has_doc, get),
        cmd!(query "procedural.errors", "Procedural Errors", [], None, "{id?} → {errors: [{node?, level: error|warning, message}]}", has_doc, errors),
        cmd!(
            "procedural.setGraph",
            "Edit Procedural Graph",
            [],
            None,
            "{id?, graph: ProcGraph JSON} replace the whole graph (its placement transform is kept unless the graph gives one) → {id, errors}",
            has_doc,
            set_graph
        ),
        cmd!(
            "procedural.addNode",
            "Add Procedural Node",
            [],
            None,
            "{id?, kind, params?: {name: value}, position?: [x, y], name?} → {node: new node id, errors}",
            has_doc,
            add_node
        ),
        cmd!("procedural.removeNode", "Remove Procedural Node", [], None, "{id?, node} remove a node and its wires → {errors}", has_doc, remove_node),
        cmd!(
            "procedural.connect",
            "Connect Procedural Nodes",
            [],
            None,
            "{id?, from: node id, to: node id, port?: input port of `to` (0)} wire `from`'s output into `to` (replacing what was there); refuses cycles → {errors}",
            has_doc,
            connect
        ),
        cmd!(
            "procedural.disconnect",
            "Disconnect Procedural Nodes",
            [],
            None,
            "{id?, to: node id, port?: (0)} unplug an input → {errors}",
            has_doc,
            disconnect
        ),
        cmd!(
            "procedural.setParam",
            "Set Procedural Parameter",
            [],
            None,
            "{id?, node, param, value} or {id?, node, params: {name: value}}: value null resets to the default; numbers are clamped to the param's range. Run it as a live interaction for slider drags (one undo step) → {errors}",
            has_doc,
            set_param
        ),
        cmd!(
            "procedural.setNode",
            "Edit Procedural Node",
            [],
            None,
            "{id?, node, position?: [x, y], name?: string|null, bypass?: bool} → {errors}",
            has_doc,
            set_node
        ),
        cmd!(
            "procedural.setOutput",
            "Set Procedural Output",
            [],
            None,
            "{id?, node: node id | null} the node whose result is the art → {errors}",
            has_doc,
            set_output
        ),
        cmd!("procedural.setSeed", "Set Procedural Seed", [], None, "{id?, seed: integer ≥ 0} → {seed, errors}", has_doc, set_seed),
        cmd!(
            "procedural.reseed",
            "Reseed",
            ["Object", "Procedural"],
            None,
            "{id?} a new random seed (derived from the old one) → {seed, errors}",
            has_doc,
            reseed
        ),
        cmd!(
            "procedural.expand",
            "Expand",
            ["Object", "Procedural"],
            None,
            "{id?} detach the art: the object becomes a plain group and its graph is dropped → {id}",
            has_doc,
            expand
        ),
    ]
}

// ---------- evaluation ----------

thread_local! {
    /// Per-object evaluation caches (keyed by everything a node's output depends on, so sharing
    /// between documents is safe: a stale entry is a miss, never a wrong result).
    static CACHES: RefCell<HashMap<NodeId, Cache>> = RefCell::new(HashMap::new());
}

/// Objects whose caches are kept (the rest are dropped; they rebuild on their next edit).
const MAX_CACHES: usize = 16;

fn evaluate(id: NodeId, g: &ProcGraph) -> procgen::Evaluation {
    CACHES.with(|c| match c.try_borrow_mut() {
        Ok(mut map) => {
            if map.len() >= MAX_CACHES && !map.contains_key(&id) {
                map.clear();
            }
            procgen::evaluate_with(g, map.entry(id).or_default())
        }
        Err(_) => procgen::evaluate(g),
    })
}

fn diags_json(d: &[Diagnostic]) -> Value {
    serde_json::to_value(d).unwrap_or(Value::Array(vec![]))
}

/// Regenerate object `id`'s children from `graph` → the evaluation's messages.
fn regenerate(d: &mut Document, id: NodeId, mut graph: ProcGraph) -> Result<Vec<Diagnostic>> {
    procgen::sanitize(&mut graph);
    let n = d.node(id).ok_or(EngineError::NoNode(id))?;
    if !matches!(n.kind, vectorcraft_doc::NodeKind::Group { .. }) {
        return Err(EngineError::Other("a procedural object must be a group".into()));
    }
    // The old children's ids go to the new ones first: fewer ids churn on every edit, which
    // keeps collaboration updates small.
    let mut pool: VecDeque<NodeId> = VecDeque::new();
    for c in n.children().into_iter().flatten() {
        c.walk(&mut |x| pool.push_back(x.id));
    }
    let ev = evaluate(id, &graph);
    let mut diags = ev.diagnostics.clone();
    let built = {
        let mut alloc = || pool.pop_front().unwrap_or_else(|| d.alloc_id());
        procgen::build_nodes(&ev.items, graph.transform, &mut alloc)
    };
    // Art pushed off the canvas would make the file unloadable: leave it out, and say so.
    let in_range =
        |n: &Arc<Node>| n.geometric_bounds().is_none_or(|r| [r.x0, r.y0, r.x1, r.y1].iter().all(|v| v.is_finite() && v.abs() <= MAX_COORD));
    let before = built.len();
    let children: Vec<Arc<Node>> = built.into_iter().filter(in_range).collect();
    if children.len() < before {
        diags.push(Diagnostic {
            node: None,
            level: Level::Warning,
            message: format!("{} objects fell outside the canvas and were left out", before - children.len()),
        });
    }
    let n = d.node_mut(id).ok_or(EngineError::NoNode(id))?;
    if let Some(ch) = n.children_mut() {
        *ch = children;
    }
    n.procedural = Some(Box::new(graph));
    Ok(diags)
}

/// The procedural object `id` names, or the selected one (or the one holding the selection).
fn target(s: &Session, p: &Value, cmd: &str) -> Result<NodeId> {
    let st = s.doc()?;
    if let Some(id) = id_param(p, "id") {
        return match st.doc.node(id) {
            Some(n) if n.procedural.is_some() => Ok(id),
            Some(_) => Err(bad(cmd, format!("object {} is not a procedural object", id.0))),
            None => Err(EngineError::NoNode(id)),
        };
    }
    for id in st.selection.objects.iter().copied() {
        let mut cur = Some(id);
        while let Some(c) = cur {
            if st.doc.node(c).is_some_and(|n| n.procedural.is_some()) {
                return Ok(c);
            }
            cur = st.doc.parent_of(c);
        }
    }
    Err(bad(cmd, "select a procedural object (or pass its id)"))
}

fn graph_of(s: &Session, id: NodeId) -> Result<ProcGraph> {
    s.doc()?.doc.node(id).and_then(|n| n.procedural.as_deref().cloned()).ok_or(EngineError::NoNode(id))
}

/// Change the target's graph with `f` and regenerate, as one undo step labelled `label`.
fn edit_graph<T>(s: &mut Session, p: &Value, cmd: &str, label: &str, f: impl FnOnce(&mut ProcGraph) -> Result<T>) -> Result<(T, Vec<Diagnostic>)> {
    let id = target(s, p, cmd)?;
    let mut g = graph_of(s, id)?;
    let r = f(&mut g)?;
    let diags = s.edit(label, |d, _| regenerate(d, id, g))?;
    Ok((r, diags))
}

fn node_param(p: &Value, key: &str, cmd: &str) -> Result<u32> {
    p.get(key).and_then(Value::as_u64).and_then(|v| u32::try_from(v).ok()).ok_or_else(|| bad(cmd, format!("missing node id `{key}`")))
}

fn has_node(g: &ProcGraph, id: u32, cmd: &str) -> Result<()> {
    if g.node(id).is_some() { Ok(()) } else { Err(bad(cmd, format!("the graph has no node {id}"))) }
}

fn position_param(p: &Value, cmd: &str) -> Result<Option<[f32; 2]>> {
    match p.get("position") {
        None | Some(Value::Null) => Ok(None),
        Some(v) => {
            let a = v.as_array().filter(|a| a.len() == 2).ok_or_else(|| bad(cmd, "position must be [x, y]"))?;
            let c = |i: usize| a.get(i).and_then(Value::as_f64).filter(|x| x.is_finite()).map(|x| x.clamp(-1.0e6, 1.0e6) as f32);
            match (c(0), c(1)) {
                (Some(x), Some(y)) => Ok(Some([x, y])),
                _ => Err(bad(cmd, "position must be two finite numbers")),
            }
        }
    }
}

fn parse_graph(v: &Value, cmd: &str) -> Result<ProcGraph> {
    let mut g: ProcGraph = serde_json::from_value(v.clone()).map_err(|e| bad(cmd, format!("not a procedural graph: {e}")))?;
    procgen::sanitize(&mut g);
    Ok(g)
}

/// A seed as JSON can carry it exactly (below 2^53).
fn js_safe(seed: u64) -> u64 {
    seed & ((1u64 << 53) - 1)
}

// ---------- commands ----------

fn create(s: &mut Session, p: &Value) -> Result<Value> {
    const C: &str = "procedural.create";
    let st = s.doc()?;
    let at = match (p.get("x").and_then(Value::as_f64), p.get("y").and_then(Value::as_f64)) {
        (Some(x), Some(y)) if x.is_finite() && y.is_finite() && x.abs() <= MAX_COORD && y.abs() <= MAX_COORD => Some(Point::new(x, y)),
        (None, None) => None,
        _ => return Err(bad(C, "x and y must both be finite numbers on the canvas")),
    };
    let centre = st.doc.artboards.first().map(|a| a.rect.center()).unwrap_or(Point::ZERO);
    let mut source: Vec<NodeId> = vec![];
    let (mut graph, label) = if let Some(v) = p.get("graph").filter(|v| !v.is_null()) {
        (parse_graph(v, C)?, "Procedural".to_string())
    } else if let Some(id) = str_param(p, "preset") {
        let g = procgen::preset(id).ok_or_else(|| bad(C, format!("unknown preset `{}`", id.chars().take(60).collect::<String>())))?;
        let label = procgen::PRESETS.iter().find(|x| x.id == id).map_or("Procedural", |x| x.label).to_string();
        (g, label)
    } else if !st.selection.is_empty() {
        source = selected_roots(s)?;
        (ProcGraph::default(), "Procedural".to_string())
    } else {
        (procgen::preset("flower").unwrap_or_default(), "Radial Flower".to_string())
    };
    if let Some(seed) = p.get("seed") {
        graph.seed = seed.as_u64().ok_or_else(|| bad(C, "seed must be a whole number ≥ 0"))?;
    }
    let name = str_param(p, "name").map(|n| n.chars().take(200).collect::<String>()).unwrap_or(label);
    let parent = s.doc()?.insertion_parent();
    let (id, diags) = s.edit("Make Procedural", |d, sel| {
        let gid = d.alloc_id();
        let mut grp = Node::group(gid, vec![]);
        grp.name = Some(name);
        let place = if source.is_empty() {
            d.insert(parent, usize::MAX, grp)?;
            at.unwrap_or(centre)
        } else {
            // The selection moves into the graph, centred on the graph origin; the object takes
            // its place in the stacking order.
            let top = *source.last().ok_or_else(|| bad(C, "nothing selected"))?;
            let (par, idx, _) = d.position(top).ok_or(EngineError::NoNode(top))?;
            let nodes: Vec<Node> = source.iter().filter_map(|id| d.node(*id).cloned()).collect();
            let bounds = nodes.iter().filter_map(Node::geometric_bounds).reduce(|a, b| a.union(b));
            let c = bounds.map_or(Point::ZERO, |b| b.center());
            let art: Vec<Arc<Node>> = nodes
                .into_iter()
                .map(|mut n| {
                    n.transform(Affine::translate(-c.to_vec2()), false);
                    Arc::new(n)
                })
                .collect();
            graph = procgen::art_graph(art);
            if let Some(seed) = p.get("seed").and_then(Value::as_u64) {
                graph.seed = seed;
            }
            d.insert(par, idx + 1, grp)?;
            for r in &source {
                d.remove(*r)?;
            }
            at.unwrap_or(c)
        };
        graph.transform = Affine::translate(place.to_vec2()) * graph.transform;
        let diags = regenerate(d, gid, graph)?;
        sel.set([gid]);
        Ok((gid, diags))
    })?;
    Ok(json!({ "id": id.0, "errors": diags_json(&diags) }))
}

fn presets(_: &mut Session, _: &Value) -> Result<Value> {
    Ok(procgen::presets_json())
}

fn catalogue(_: &mut Session, _: &Value) -> Result<Value> {
    Ok(procgen::catalogue_json())
}

fn get(s: &mut Session, p: &Value) -> Result<Value> {
    let id = target(s, p, "procedural.get")?;
    let g = graph_of(s, id)?;
    let ev = evaluate(id, &g);
    Ok(json!({
        "id": id.0,
        "graph": serde_json::to_value(&g).unwrap_or(Value::Null),
        "errors": diags_json(&ev.diagnostics),
        "items": ev.items.len(),
    }))
}

fn errors(s: &mut Session, p: &Value) -> Result<Value> {
    let id = target(s, p, "procedural.errors")?;
    let g = graph_of(s, id)?;
    Ok(json!({ "errors": diags_json(&evaluate(id, &g).diagnostics) }))
}

fn set_graph(s: &mut Session, p: &Value) -> Result<Value> {
    const C: &str = "procedural.setGraph";
    let v = p.get("graph").ok_or_else(|| bad(C, "missing `graph`"))?;
    let mut new = parse_graph(v, C)?;
    let keeps_placement = v.get("transform").is_none();
    let id = target(s, p, C)?;
    let (_, diags) = edit_graph(s, p, C, "Edit Procedural Graph", |g| {
        if keeps_placement {
            new.transform = g.transform;
        }
        *g = new;
        Ok(())
    })?;
    Ok(json!({ "id": id.0, "errors": diags_json(&diags) }))
}

fn add_node(s: &mut Session, p: &Value) -> Result<Value> {
    const C: &str = "procedural.addNode";
    let kind = str_param(p, "kind").ok_or_else(|| bad(C, "missing `kind`"))?.to_string();
    let params: Map<String, Value> = match p.get("params") {
        None | Some(Value::Null) => Map::new(),
        Some(Value::Object(m)) => m.clone(),
        Some(_) => return Err(bad(C, "params must be an object")),
    };
    let position = position_param(p, C)?;
    let name = str_param(p, "name").map(|n| n.chars().take(200).collect::<String>());
    let (node, diags) = edit_graph(s, p, C, "Add Procedural Node", |g| {
        if g.nodes.len() >= procgen::limits::MAX_NODES {
            return Err(bad(C, format!("a graph holds at most {} nodes", procgen::limits::MAX_NODES)));
        }
        let mut n = procgen::new_node(g, &kind, &params).map_err(|e| bad(C, e))?;
        n.position = position.unwrap_or([0.0, 0.0]);
        n.name = name;
        let id = n.id;
        g.nodes.push(n);
        Ok(id)
    })?;
    Ok(json!({ "node": node, "errors": diags_json(&diags) }))
}

fn remove_node(s: &mut Session, p: &Value) -> Result<Value> {
    const C: &str = "procedural.removeNode";
    let node = node_param(p, "node", C)?;
    let (_, diags) = edit_graph(s, p, C, "Remove Procedural Node", |g| {
        has_node(g, node, C)?;
        g.nodes.retain(|n| n.id != node);
        for n in &mut g.nodes {
            for l in n.inputs.iter_mut() {
                if l.is_some_and(|l| l.node == node) {
                    *l = None;
                }
            }
            while n.inputs.last().is_some_and(Option::is_none) {
                n.inputs.pop();
            }
        }
        if g.output.is_some_and(|o| o.node == node) {
            g.output = None;
        }
        Ok(())
    })?;
    Ok(json!({ "errors": diags_json(&diags) }))
}

fn port_param(p: &Value, cmd: &str) -> Result<usize> {
    match p.get("port") {
        None | Some(Value::Null) => Ok(0),
        Some(v) => v.as_u64().and_then(|x| usize::try_from(x).ok()).ok_or_else(|| bad(cmd, "port must be a whole number ≥ 0")),
    }
}

fn connect(s: &mut Session, p: &Value) -> Result<Value> {
    const C: &str = "procedural.connect";
    let (from, to) = (node_param(p, "from", C)?, node_param(p, "to", C)?);
    let port = port_param(p, C)?;
    let (_, diags) = edit_graph(s, p, C, "Connect Procedural Nodes", |g| {
        has_node(g, from, C)?;
        let target = g.node(to).ok_or_else(|| bad(C, format!("the graph has no node {to}")))?;
        let spec = procgen::spec(&target.kind).ok_or_else(|| bad(C, format!("node {to} has an unknown kind")))?;
        let ports = if spec.variadic { procgen::limits::MAX_PORTS } else { spec.inputs.len() };
        if port >= ports {
            return Err(bad(C, format!("node {to} ({}) has {ports} input port(s)", spec.kind)));
        }
        if procgen::would_cycle(g, from, to) {
            return Err(bad(C, "that wire would make a cycle"));
        }
        let n = g.node_mut(to).ok_or_else(|| bad(C, format!("the graph has no node {to}")))?;
        if n.inputs.len() <= port {
            n.inputs.resize(port + 1, None);
        }
        if let Some(slot) = n.inputs.get_mut(port) {
            *slot = Some(Link::new(from));
        }
        Ok(())
    })?;
    Ok(json!({ "errors": diags_json(&diags) }))
}

fn disconnect(s: &mut Session, p: &Value) -> Result<Value> {
    const C: &str = "procedural.disconnect";
    let to = node_param(p, "to", C)?;
    let port = port_param(p, C)?;
    let (_, diags) = edit_graph(s, p, C, "Disconnect Procedural Nodes", |g| {
        let n = g.node_mut(to).ok_or_else(|| bad(C, format!("the graph has no node {to}")))?;
        if let Some(slot) = n.inputs.get_mut(port) {
            *slot = None;
        }
        while n.inputs.last().is_some_and(Option::is_none) {
            n.inputs.pop();
        }
        Ok(())
    })?;
    Ok(json!({ "errors": diags_json(&diags) }))
}

fn set_param(s: &mut Session, p: &Value) -> Result<Value> {
    const C: &str = "procedural.setParam";
    let node = node_param(p, "node", C)?;
    let mut changes: Vec<(String, Value)> = vec![];
    if let Some(m) = p.get("params") {
        let m = m.as_object().ok_or_else(|| bad(C, "params must be an object"))?;
        changes.extend(m.iter().map(|(k, v)| (k.clone(), v.clone())));
    }
    if let Some(k) = str_param(p, "param") {
        changes.push((k.to_string(), p.get("value").cloned().unwrap_or(Value::Null)));
    }
    if changes.is_empty() {
        return Err(bad(C, "give `param` and `value`, or `params`"));
    }
    let (_, diags) = edit_graph(s, p, C, "Set Procedural Parameter", |g| {
        let n = g.node_mut(node).ok_or_else(|| bad(C, format!("the graph has no node {node}")))?;
        let spec = procgen::spec(&n.kind).ok_or_else(|| bad(C, format!("node {node} has an unknown kind")))?;
        for (k, v) in changes {
            let ps = spec
                .params
                .iter()
                .find(|x| x.name == k)
                .ok_or_else(|| bad(C, format!("`{}` has no parameter `{}`", spec.kind, k.chars().take(60).collect::<String>())))?;
            if v.is_null() {
                n.params.remove(&k);
            } else {
                n.params.insert(k, ps.check(&v).map_err(|e| bad(C, e))?);
            }
        }
        Ok(())
    })?;
    Ok(json!({ "errors": diags_json(&diags) }))
}

fn set_node(s: &mut Session, p: &Value) -> Result<Value> {
    const C: &str = "procedural.setNode";
    let node = node_param(p, "node", C)?;
    let position = position_param(p, C)?;
    let name = match p.get("name") {
        None => None,
        Some(Value::Null) => Some(None),
        Some(Value::String(n)) => Some(Some(n.chars().take(200).collect::<String>())),
        Some(_) => return Err(bad(C, "name must be a string or null")),
    };
    let bypass = match p.get("bypass") {
        None => None,
        Some(v) => Some(v.as_bool().ok_or_else(|| bad(C, "bypass must be true or false"))?),
    };
    let (_, diags) = edit_graph(s, p, C, "Edit Procedural Node", |g| {
        let n = g.node_mut(node).ok_or_else(|| bad(C, format!("the graph has no node {node}")))?;
        if let Some(pos) = position {
            n.position = pos;
        }
        if let Some(name) = name {
            n.name = name;
        }
        if let Some(b) = bypass {
            n.bypass = b;
        }
        Ok(())
    })?;
    Ok(json!({ "errors": diags_json(&diags) }))
}

fn set_output(s: &mut Session, p: &Value) -> Result<Value> {
    const C: &str = "procedural.setOutput";
    let node = match p.get("node") {
        Some(Value::Null) => None,
        _ => Some(node_param(p, "node", C)?),
    };
    let (_, diags) = edit_graph(s, p, C, "Set Procedural Output", |g| {
        if let Some(n) = node {
            has_node(g, n, C)?;
        }
        g.output = node.map(Link::new);
        Ok(())
    })?;
    Ok(json!({ "errors": diags_json(&diags) }))
}

fn set_seed(s: &mut Session, p: &Value) -> Result<Value> {
    const C: &str = "procedural.setSeed";
    let seed = p.get("seed").and_then(Value::as_u64).ok_or_else(|| bad(C, "seed must be a whole number ≥ 0"))?;
    let (_, diags) = edit_graph(s, p, C, "Set Procedural Seed", |g| {
        g.seed = seed;
        Ok(())
    })?;
    Ok(json!({ "seed": seed, "errors": diags_json(&diags) }))
}

fn reseed(s: &mut Session, p: &Value) -> Result<Value> {
    // Derived from the old seed, so replaying the journal gives the same art.
    let (seed, diags) = edit_graph(s, p, "procedural.reseed", "Reseed", |g| {
        g.seed = js_safe(procgen::math::mix64(g.seed));
        Ok(g.seed)
    })?;
    Ok(json!({ "seed": seed, "errors": diags_json(&diags) }))
}

fn expand(s: &mut Session, p: &Value) -> Result<Value> {
    let id = target(s, p, "procedural.expand")?;
    s.edit("Expand Procedural", |d, sel| {
        let n = d.node_mut(id).ok_or(EngineError::NoNode(id))?;
        n.procedural = None;
        sel.set([id]);
        Ok(())
    })?;
    Ok(json!({ "id": id.0 }))
}
